audit_header: false
title:
description: Mike Wall, a top Real Estate Agent in Cincinnati and Dayton, shares his own internal real estate agent training for free. His Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: false
custom_links:
  - title: Join Our Team
    url: http://mikewall.exprealty.careers/
  - title: Free Strategy Call
    url: https://calendly.com/mike-77/exp/09-19-2018
  - title: Webinars
    url: http://www.gcimultiplier.com/gotomeeting/register.php

client:
  name: Mike Wall
  title:
  license_number:
  about_markdown: |
    The Love Ohio Living Team, founded and headquartered in Ohio, is one of the fastest growing real estate teams in the country — ranked by The Board of Realtors as the #1 Real Estate Team at eXp Realty is focused on dominating Cincinnati & Dayton

    The standard of The Love Ohio Living Team is to provide clients with the highest level of service through our innovative and client-centered team approach to selling homes. When you work with The Love Ohio Living Team gives you piece of mind with guarantees such as our Sold in 77 Program, 24-Month Love it or List it Guarantee, and more!
  market: Cincinnati and Dayton
  brand:  Love Ohio Living Team
  brokerage: Brokered by eXp Realty
  location1: Cincinnati
  address: 7185 Liberty Centre Dr. Ste. F<br>West Chester, OH 45069
  phone: 513-299-8999
  location2: Dayton
  address2: 6788 Loop Rd.<br>Centerville, OH 45459
  phone2: 937-240-0999
  email: mike@loveohioliving.com
  url: http://loveohioliving.com

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "Join Our Team"
    CTA_text: "Sell More Homes in Less Time"
    CTA_link_text: "Apply Now"
    CTA_url: http://mikewall.exprealty.careers/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Free Strategy Call"
    CTA_text2: "Personalized Advice For You"
    CTA_link_text2: "Get in Touch"
    CTA_url2: https://calendly.com/mike-77/exp/09-19-2018

third_sidebar_CTA:
  - CTA_image_path3: /img/cta-images/003.jpg
    CTA_title3: "Live Real Estate Coaching"
    CTA_text3: "You pick the topic and we'll dive deep for 45 minutes!"
    CTA_link_text3: "Free Coaching Session"
    CTA_url3: http://www.liverealestatecoaching.com/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/LoveOhioLiving/
  linkedin_url: https://www.linkedin.com/in/daytonohiorealestate/
  gplus_url:
  youtube_url: https://www.youtube.com/mikewallrealtor
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Cincinnati and Dayton Real Estate Podcast with Mike Wall'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Cincinnati and Dayton Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Love Ohio Living Team - your professional Cincinnati and Dayton Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Cincinnati and Dayton, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Mike Wall'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/eXp-logo.png
  logo_width_number: 40
  hero_text: Cincinnati and Dayton Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#f5821f'
  theme_color: '#19469d'
  accent_color: '#f9a81a'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#1C2841'

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
